In [5]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv('Iris.csv')

In [7]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [8]:
df=df.drop('Id',axis=1)

In [9]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [10]:
df['Species']=np.where(df['Species']=="Iris-setosa",0,np.where(df['Species']=="Iris-virginica",2,1))
df.sample(5)

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
84            5.4           3.0            4.5           1.5        1
99            5.7           2.8            4.1           1.3        1
77            6.7           3.0            5.0           1.7        1
5             5.4           3.9            1.7           0.4        0
21            5.1           3.7            1.5           0.4        0

In [11]:
X=df.iloc[:,0:4]
y=df.iloc[:,-1]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1)

In [14]:
y_train

118    2
18     0
4      0
45     0
59     1
      ..
133    2
137    2
72     1
140    2
37     0
Name: Species, Length: 105, dtype: int64

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [16]:
clf=LogisticRegression(multi_class='multinomial')
clf2=DecisionTreeClassifier()

In [17]:
clf.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\nbhar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

DecisionTreeClassifier()

In [18]:
y_pred=clf.predict(X_test)
Y_pred=clf2.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [20]:
print(accuracy_score(y_test,y_pred))
print(accuracy_score(y_test,Y_pred))

0.9777777777777777
0.9555555555555556

In [21]:
confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 13]])

In [22]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [24]:
print("Precision - ",precision_score(y_test,y_pred,average=None))
print("Recall - ",recall_score(y_test,y_pred,average=None))
print("F1 score - ",f1_score(y_test,y_pred,average=None))

Precision -  [1.         1.         0.92857143]
Recall -  [1.         0.94444444 1.        ]
F1 score -  [1.         0.97142857 0.96296296]

In [25]:
print("Precision - ",precision_score(y_test,Y_pred,average=None))
print("Recall - ",recall_score(y_test,Y_pred,average=None))
print("F1 score - ",f1_score(y_test,Y_pred,average=None))

Precision -  [1.         0.94444444 0.92307692]
Recall -  [1.         0.94444444 0.92307692]
F1 score -  [1.         0.94444444 0.92307692]